# Generated by Django 4.2 on 2023-04-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="case_table",
        ),
    ]
