# Generated by Django 4.2 on 2023-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="active_lawsuits_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="active_lawsuits_images/")),
                ("text", models.TextField(max_length=2000)),
            ],
        ),
    ]
