# Generated by Django 4.2 on 2023-04-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("active_lawsuits", "0002_active_lawsuit_table_delete_active_lawsuits_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="active_law_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("card_image", models.ImageField(upload_to="active_lawsuits_images/")),
                (
                    "banner_image",
                    models.ImageField(upload_to="active_lawsuits_images/"),
                ),
                ("text", models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name="active_lawsuit_table",
        ),
    ]
