# Generated by Django 4.2 on 2023-04-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("active_lawsuits", "0004_active_law_table_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="active_law_table",
            name="heading",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
