# Generated by Django 4.2 on 2023-04-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contact_us_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email_address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=1000)),
            ],
        ),
    ]
